# Generated by Django 3.1.7 on 2021-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_addproject_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='addproject',
            name='comment',
        ),
    ]
