# Generated by Django 3.1.7 on 2021-03-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0006_auto_20210319_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='donnate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
