# Generated by Django 3.1.7 on 2021-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_auto_20210324_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
