# Generated by Django 3.1.7 on 2021-03-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0009_addproject_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='uploadimg',
            field=models.ImageField(upload_to=''),
        ),
    ]
