# Generated by Django 3.1.7 on 2021-03-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0011_featureproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='tags',
        ),
    ]
